export * from './registration-page'
export * from './authorization-page'
export * from './recover-password-page'
export * from './catalog-page'
export * from './product-card-page'
export * from './main'
